import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome_title: "Welcome to the Axum Training Curriculum",
    welcome_description: "Your journey to mastering the art of hair styling starts here. Track your progress, complete lessons, and unlock your potential.",
    your_progress: "Your Progress",
    loading_session: "Loading user session...",
    sign_in_prompt: "Please sign in to track your progress and access full features.",
    go_to_login: "Go to Login",
    continue_learning: "Continue Learning",
    review_curriculum: "Review Curriculum",
    completed_all_lessons: "You've completed all lessons! Congratulations!",
    curriculum_phases: "Curriculum Phases",
    no_phases_found: "No curriculum phases found.",
    lessons_plural: "Lessons",
    lesson_singular: "Lesson",
    duration_weeks: "Duration: {{weeks}} Weeks",
    sign_in: "Sign In",
    sign_out: "Sign Out",
    admin_dashboard: "Admin Dashboard",
    email_address: "Email address",
    your_email_address: "Your email address",
    send_magic_link: "Send Magic Link",
    sending: "Sending...",
    objectives: "Objectives",
    video_demonstration: "Video Demonstration",
    resources: "Resources",
    download_resources: "Download Resources",
    knowledge_check_quiz: "Knowledge Check Quiz",
    completed: "Completed!",
    mark_complete: "Mark Complete",
    next_lesson: "Next Lesson",
    read_aloud: "Read Aloud",
    stop_reading: "Stop Reading",
    browser_no_tts: "Your browser does not support text-to-speech.",
    tts_error: "An error occurred during text-to-speech.",
    module_not_found: "Module not found.",
    return_to_phase: "Return to Phase",
    lessons_in_this_module: "Lessons in this Module",
    manage_lessons: "Manage Lessons",
    phase_not_found: "Phase not found.",
    return_to_curriculum: "Return to Curriculum",
    modules_for_weeks: "Modules ({{weeks}} Weeks)",
    manage_modules: "Manage Modules",
    quiz_title: "Quiz",
    quiz_passed_congrats: "Congratulations! You passed with a score of {{score}}%.",
    quiz_attempts_used: "You have used all {{maxAttempts}} attempts. Your best score was {{bestScore}}%.",
    quiz_can_attempt: "Attempt {{currentAttempt}} of {{maxAttempts}}. You need {{passingScore}}% to pass.",
    quiz_login_required: "Please log in to take the quiz.",
    quiz_no_questions: "No questions available for this quiz yet.",
    quiz_correct: "Correct!",
    quiz_incorrect: "Incorrect.",
    quiz_correct_answer: "Correct answer",
    submit_attempt: "Submit Attempt {{currentAttempt}}",
    submitting: "Submitting...",
    take_attempt: "Take Attempt {{currentAttempt}}",
    score_for_attempt: "Score for this attempt: {{score}}%",
    lesson_marked_complete: "Lesson marked as complete!",
    lesson_mark_complete_failed: "Failed to mark lesson complete: {{message}}",
    quiz_submit_failed: "Failed to submit quiz: {{message}}",
    quiz_score_too_low: "Quiz score too low to mark lesson complete. Please review and try again.",
    must_be_logged_in_to_mark_complete: "You must be logged in to mark lessons complete.",
    access_denied: "Access Denied",
    no_permission: "You do not have permission to view this page.",
    return_to_home: "Return to Home",
    loading_user_role: "Loading user role...",
    phase_id_missing: "Phase ID missing.",
    return_to_phase_management: "Return to Phase Management",
    modules_for: "Modules for \"{{title}}\"",
    add_new_module: "Add New Module",
    no_modules_found: "No modules found for this phase. Click \"Add New Module\" to get started!",
    edit_module: "Edit Module",
    delete_module: "Delete Module",
    are_you_sure: "Are you absolutely sure?",
    delete_module_description: "This action cannot be undone. This will permanently delete the module and all associated lessons and quizzes.",
    cancel: "Cancel",
    delete: "Delete",
    lessons_for: "Lessons for \"{{title}}\"",
    add_new_lesson: "Add New Lesson",
    no_lessons_found: "No lessons found. Click \"Add New Lesson\" to get started!",
    edit_lesson: "Edit Lesson",
    delete_lesson: "Delete Lesson",
    delete_lesson_description: "This will permanently delete the lesson.",
    manage_curriculum_phases: "Manage Curriculum Phases",
    add_new_phase: "Add New Phase",
    no_phases_found_admin: "No phases found. Click \"Add New Phase\" to get started!",
    edit_phase: "Edit Phase",
    delete_phase: "Delete Phase",
    delete_phase_description: "This action cannot be undone. This will permanently delete the phase and all associated modules, lessons, and quizzes.",
    manage_quizzes: "Manage Quizzes",
    add_new_quiz: "Add New Quiz",
    no_quizzes_found: "No quizzes found. Click \"Add New Quiz\" to get started!",
    edit_quiz: "Edit Quiz",
    delete_quiz: "Delete Quiz",
    delete_quiz_description: "This will permanently delete the quiz and all its questions.",
    questions_for: "Questions for \"{{title}}\"",
    add_new_question: "Add New Question",
    no_questions_found: "No questions found. Click \"Add New Question\" to get started!",
    edit_question: "Edit Question",
    delete_question: "Delete Question",
    delete_question_description: "This will permanently delete the question.",
    question_text: "Question Text",
    options: "Options",
    add_option: "Add Option",
    correct_answer: "Correct Answer",
    save_question: "Save Question",
    saving: "Saving...",
    title: "Title",
    description: "Description",
    duration_weeks_label: "Duration (Weeks)",
    order_index: "Order Index",
    update_phase: "Update Phase",
    add_phase: "Add Phase",
    module_title: "Module Title",
    update_module: "Update Module",
    add_module: "Add Module",
    lesson_title: "Lesson Title",
    content_html: "Content (HTML)",
    video_url: "Video URL",
    resources_url: "Resources URL",
    quiz: "Quiz",
    no_quiz: "No Quiz",
    select_a_quiz: "Select a quiz",
    save_lesson: "Save Lesson",
    save_quiz: "Save Quiz",
    admin_dashboard_title: "Admin Dashboard",
    admin_dashboard_welcome: "Welcome, Admin! This is where you can manage various aspects of the platform.",
    manage_curriculum: "Manage Curriculum",
    manage_curriculum_description: "Add, edit, or remove phases, modules, and lessons.",
    go_to_curriculum_management: "Go to Curriculum Management",
    manage_users: "Manage Users",
    manage_users_description: "View and manage user accounts and roles.",
    go_to_user_management: "Go to User Management",
    view_reports: "View Reports",
    view_reports_description: "Access student progress and quiz performance reports.",
    go_to_reports: "Go to Reports",
    manage_users_page_title: "Manage Users",
    edit_role_for: "Edit Role for {{email}}",
    name: "Name",
    email: "Email",
    role: "Role",
    actions: "Actions",
    edit_role: "Edit Role",
    user_role_updated: "User role updated successfully!",
    failed_to_update_role: "Failed to update role: {{message}}",
    user: "User",
    admin: "Admin",
    select_a_role: "Select a role",
    save_role: "Save Role",
    logout_failed: "Logout failed: {{message}}",
    logged_out: "You have been logged out.",
    failed_to_load_profile: "Failed to load user profile: {{message}}",
    unexpected_error_session_check: "An unexpected error occurred during session check: {{message}}",
    failed_to_get_initial_session: "Failed to get initial session: {{message}",
    failed_to_load_phases: "Failed to load phases: {{message}}",
    phase_deleted_successfully: "Phase deleted successfully!",
    failed_to_delete_phase: "Failed to delete phase: {{message}}",
    phase_updated_successfully: "Phase updated successfully!",
    phase_added_successfully: "Phase added successfully!",
    failed_to_save_phase: "Failed to save phase: {{message}}",
    failed_to_load_modules: "Failed to load modules: {{message}}",
    module_deleted_successfully: "Module deleted successfully!",
    failed_to_delete_module: "Failed to delete module: {{message}}",
    module_updated_successfully: "Module updated successfully!",
    module_added_successfully: "Module added successfully!",
    failed_to_save_module: "Failed to save module: {{message}}",
    failed_to_load_lessons: "Failed to load lessons: {{message}}",
    lesson_deleted_successfully: "Lesson deleted successfully!",
    failed_to_delete_lesson: "Failed to delete lesson: {{message}}",
    lesson_updated_successfully: "Lesson updated successfully!",
    lesson_added_successfully: "Lesson added successfully!",
    failed_to_save_lesson: "Failed to save lesson: {{message}}",
    failed_to_load_quizzes: "Failed to load quizzes: {{message}}",
    quiz_deleted_successfully: "Quiz deleted successfully!",
    failed_to_delete_quiz: "Failed to delete quiz: {{message}}",
    quiz_updated_successfully: "Quiz updated successfully!",
    quiz_added_successfully: "Quiz added successfully!",
    failed_to_save_quiz: "Failed to save quiz: {{message}}",
    failed_to_load_questions: "Failed to load questions: {{message}}",
    question_deleted_successfully: "Question deleted successfully!",
    failed_to_delete_question: "Failed to delete question: {{message}}",
    question_updated_successfully: "Question updated successfully!",
    question_added_successfully: "Question added successfully!",
    failed_to_save_question: "Failed to save question: {{message}",
    failed_to_load_users: "Failed to load users: {{message}}",
    failed_to_load_quiz: "Failed to load quiz: {{message}}",
    attempt_submitted: "Attempt {{attemptNum}} submitted! Your score: {{score}}%",
    login_prompt_message: "Sign in with your email to access the curriculum.",
    complete_profile_title: "Complete Your Profile",
    complete_profile_description: "Please provide your first and last name to personalize your learning experience.",
    first_name: "First Name",
    last_name: "Last Name",
    save_profile: "Save Profile",
    saving_profile: "Saving Profile...",
    profile_updated_successfully: "Profile updated successfully!",
    failed_to_update_profile: "Failed to update profile: {{message}}",
  },
  fr: {
    welcome_title: "Bienvenue au programme de formation Axum",
    welcome_description: "Votre parcours pour maîtriser l'art de la coiffure commence ici. Suivez vos progrès, complétez les leçons et libérez votre potentiel.",
    your_progress: "Votre progression",
    loading_session: "Chargement de la session utilisateur...",
    sign_in_prompt: "Veuillez vous connecter pour suivre vos progrès et accéder à toutes les fonctionnalités.",
    go_to_login: "Aller à la connexion",
    continue_learning: "Continuer l'apprentissage",
    review_curriculum: "Revoir le programme",
    completed_all_lessons: "Vous avez terminé toutes les leçons ! Félicitations !",
    curriculum_phases: "Phases du programme",
    no_phases_found: "Aucune phase de programme trouvée.",
    lessons_plural: "Leçons",
    lesson_singular: "Leçon",
    duration_weeks: "Durée : {{weeks}} Semaines",
    sign_in: "Se connecter",
    sign_out: "Se déconnecter",
    admin_dashboard: "Tableau de bord administrateur",
    email_address: "Adresse e-mail",
    your_email_address: "Votre adresse e-mail",
    send_magic_link: "Envoyer le lien magique",
    sending: "Envoi...",
    objectives: "Objectifs",
    video_demonstration: "Démonstration vidéo",
    resources: "Ressources",
    download_resources: "Télécharger les ressources",
    knowledge_check_quiz: "Quiz de vérification des connaissances",
    completed: "Terminé !",
    mark_complete: "Marquer comme terminé",
    next_lesson: "Leçon suivante",
    read_aloud: "Lire à voix haute",
    stop_reading: "Arrêter la lecture",
    browser_no_tts: "Votre navigateur ne prend pas en charge la synthèse vocale.",
    tts_error: "Une erreur est survenue lors de la synthèse vocale.",
    module_not_found: "Module introuvable.",
    return_to_phase: "Retour à la phase",
    lessons_in_this_module: "Leçons de ce module",
    manage_lessons: "Gérer les leçons",
    phase_not_found: "Phase introuvable.",
    return_to_curriculum: "Retour au programme",
    modules_for_weeks: "Modules ({{weeks}} Semaines)",
    manage_modules: "Gérer les modules",
    quiz_title: "Quiz",
    quiz_passed_congrats: "Félicitations ! Vous avez réussi avec un score de {{score}}%.",
    quiz_attempts_used: "Vous avez utilisé toutes les {{maxAttempts}} tentatives. Votre meilleur score était de {{bestScore}}%.",
    quiz_can_attempt: "Tentative {{currentAttempt}} sur {{maxAttempts}}. Vous avez besoin de {{passingScore}}% pour réussir.",
    quiz_login_required: "Veuillez vous connecter pour faire le quiz.",
    quiz_no_questions: "Aucune question disponible pour ce quiz pour le moment.",
    quiz_correct: "Correct !",
    quiz_incorrect: "Incorrect.",
    quiz_correct_answer: "Bonne réponse",
    submit_attempt: "Soumettre la tentative {{currentAttempt}}",
    submitting: "Soumission...",
    take_attempt: "Faire la tentative {{currentAttempt}}",
    score_for_attempt: "Score pour cette tentative : {{score}}%",
    lesson_marked_complete: "Leçon marquée comme terminée !",
    lesson_mark_complete_failed: "Échec de la marque de leçon comme terminée : {{message}}",
    quiz_submit_failed: "Échec de la soumission du quiz : {{message}}",
    quiz_score_too_low: "Score du quiz trop faible pour marquer la leçon comme terminée. Veuillez réviser et réessayer.",
    must_be_logged_in_to_mark_complete: "Vous devez être connecté pour marquer les leçons comme terminées.",
    access_denied: "Accès refusé",
    no_permission: "Vous n'avez pas la permission de voir cette page.",
    return_to_home: "Retour à l'accueil",
    loading_user_role: "Chargement du rôle utilisateur...",
    phase_id_missing: "ID de phase manquant.",
    return_to_phase_management: "Retour à la gestion des phases",
    modules_for: "Modules pour \"{{title}}\"",
    add_new_module: "Ajouter un nouveau module",
    no_modules_found: "Aucun module trouvé pour cette phase. Cliquez sur \"Ajouter un nouveau module\" pour commencer !",
    edit_module: "Modifier le module",
    delete_module: "Supprimer le module",
    are_you_sure: "Êtes-vous absolument sûr(e) ?",
    delete_module_description: "Cette action est irréversible. Cela supprimera définitivement la phase et tous les modules, leçons et quiz associés.",
    cancel: "Annuler",
    delete: "Supprimer",
    lessons_for: "Leçons pour \"{{title}}\"",
    add_new_lesson: "Ajouter une nouvelle leçon",
    no_lessons_found: "Aucune leçon trouvée. Cliquez sur \"Ajouter une nouvelle leçon\" pour commencer !",
    edit_lesson: "Modifier la leçon",
    delete_lesson: "Supprimer la leçon",
    delete_lesson_description: "Cela supprimera définitivement la leçon.",
    manage_curriculum_phases: "Gérer les phases du programme",
    add_new_phase: "Ajouter une nouvelle phase",
    no_phases_found_admin: "Aucune phase trouvée. Cliquez sur \"Ajouter une nouvelle phase\" pour commencer !",
    edit_phase: "Modifier la phase",
    delete_phase: "Supprimer la phase",
    delete_phase_description: "Cette action est irréversible. Cela supprimera définitivement la phase et tous les modules, leçons et quiz associés.",
    manage_quizzes: "Gérer les quiz",
    add_new_quiz: "Ajouter un nouveau quiz",
    no_quizzes_found: "Aucun quiz trouvé. Cliquez sur \"Ajouter un nouveau quiz\" pour commencer !",
    edit_quiz: "Modifier le quiz",
    delete_quiz: "Supprimer le quiz",
    delete_quiz_description: "Cela supprimera définitivement le quiz et toutes ses questions.",
    questions_for: "Questions pour \"{{title}}\"",
    add_new_question: "Ajouter une nouvelle question",
    no_questions_found: "Aucune question trouvée. Cliquez sur \"Ajouter une nouvelle question\" pour commencer !",
    edit_question: "Modifier la question",
    delete_question: "Supprimer la question",
    delete_question_description: "Cela supprimera définitivement la question.",
    question_text: "Texte de la question",
    options: "Options",
    add_option: "Ajouter une option",
    correct_answer: "Bonne réponse",
    save_question: "Enregistrer la question",
    saving: "Enregistrement...",
    title: "Titre",
    description: "Description",
    duration_weeks_label: "Durée (Semaines)",
    order_index: "Ordre",
    update_phase: "Mettre à jour la phase",
    add_phase: "Ajouter une phase",
    module_title: "Titre du module",
    update_module: "Mettre à jour le module",
    add_module: "Ajouter un module",
    lesson_title: "Titre de la leçon",
    content_html: "Contenu (HTML)",
    video_url: "URL de la vidéo",
    resources_url: "URL des ressources",
    quiz: "Quiz",
    no_quiz: "Pas de quiz",
    select_a_quiz: "Sélectionner un quiz",
    save_lesson: "Enregistrer la leçon",
    save_quiz: "Enregistrer le quiz",
    admin_dashboard_title: "Tableau de bord administrateur",
    admin_dashboard_welcome: "Bienvenue, Admin ! C'est ici que vous pouvez gérer les différents aspects de la plateforme.",
    manage_curriculum: "Gérer le programme",
    manage_curriculum_description: "Ajouter, modifier ou supprimer des phases, des modules et des leçons.",
    go_to_curriculum_management: "Aller à la gestion du programme",
    manage_users: "Gérer les utilisateurs",
    manage_users_description: "Afficher et gérer les comptes et les rôles des utilisateurs.",
    go_to_user_management: "Aller à la gestion des utilisateurs",
    view_reports: "Voir les rapports",
    view_reports_description: "Accéder aux rapports de progression des étudiants et de performance des quiz.",
    go_to_reports: "Aller aux rapports",
    manage_users_page_title: "Gérer les utilisateurs",
    edit_role_for: "Modifier le rôle de {{email}}",
    name: "Nom",
    email: "E-mail",
    role: "Rôle",
    actions: "Actions",
    edit_role: "Modifier le rôle",
    user_role_updated: "Rôle utilisateur mis à jour avec succès !",
    failed_to_update_role: "Échec de la mise à jour du rôle : {{message}}",
    user: "Utilisateur",
    admin: "Administrateur",
    select_a_role: "Sélectionner un rôle",
    save_role: "Enregistrer le rôle",
    logout_failed: "Échec de la déconnexion : {{message}}",
    logged_out: "Vous avez été déconnecté(e).",
    failed_to_load_profile: "Échec du chargement du profil utilisateur : {{message}}",
    unexpected_error_session_check: "Une erreur inattendue est survenue lors de la vérification de la session : {{message}}",
    failed_to_get_initial_session: "Échec de l'obtention de la session initiale : {{message}}",
    failed_to_load_phases: "Échec du chargement des phases : {{message}}",
    phase_deleted_successfully: "Phase supprimée avec succès !",
    failed_to_delete_phase: "Échec de la suppression de la phase : {{message}}",
    phase_updated_successfully: "Phase mise à jour avec succès !",
    phase_added_successfully: "Phase ajoutée avec succès !",
    failed_to_save_phase: "Échec de l'enregistrement de la phase : {{message}}",
    failed_to_load_modules: "Échec du chargement des modules : {{message}}",
    module_deleted_successfully: "Module supprimé avec succès !",
    failed_to_delete_module: "Échec de la suppression du module : {{message}}",
    module_updated_successfully: "Module mis à jour avec succès !",
    module_added_successfully: "Module ajouté avec succès !",
    failed_to_save_module: "Échec de l'enregistrement du module : {{message}}",
    failed_to_load_lessons: "Échec du chargement des leçons : {{message}}",
    lesson_deleted_successfully: "Leçon supprimée avec succès !",
    failed_to_delete_lesson: "Échec de la suppression de la leçon : {{message}}",
    lesson_updated_successfully: "Leçon mise à jour avec succès !",
    lesson_added_successfully: "Leçon ajoutée avec succès !",
    failed_to_save_lesson: "Échec de l'enregistrement de la leçon : {{message}}",
    failed_to_load_quizzes: "Échec du chargement des quiz : {{message}}",
    quiz_deleted_successfully: "Quiz supprimé avec succès !",
    failed_to_delete_quiz: "Échec de la suppression du quiz : {{message}}",
    quiz_updated_successfully: "Quiz mis à jour avec succès !",
    quiz_added_successfully: "Quiz ajouté avec succès !",
    failed_to_save_quiz: "Échec de l'enregistrement du quiz : {{message}}",
    failed_to_load_questions: "Échec du chargement des questions : {{message}}",
    question_deleted_successfully: "Question supprimée avec succès !",
    failed_to_delete_question: "Échec de la suppression de la question : {{message}}",
    question_updated_successfully: "Question mise à jour avec succès !",
    question_added_successfully: "Question ajoutée avec succès !",
    failed_to_save_question: "Échec de l'enregistrement de la question : {{message}}",
    failed_to_load_users: "Échec du chargement des utilisateurs : {{message}}",
    failed_to_load_quiz: "Échec du chargement du quiz : {{message}}",
    attempt_submitted: "Tentative {{attemptNum}} soumise ! Votre score : {{score}}%",
    login_prompt_message: "Connectez-vous avec votre e-mail pour accéder au programme.",
    complete_profile_title: "Complétez votre profil",
    complete_profile_description: "Veuillez indiquer votre prénom et votre nom pour personnaliser votre expérience d'apprentissage.",
    first_name: "Prénom",
    last_name: "Nom de famille",
    save_profile: "Enregistrer le profil",
    saving_profile: "Enregistrement du profil...",
    profile_updated_successfully: "Profil mis à jour avec succès !",
    failed_to_update_profile: "Échec de la mise à jour du profil : {{message}}",
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en'); // Default to English

  const t = (key: string, params?: Record<string, string | number>) => {
    let translated = translations[language][key] || translations['en'][key] || key;
    if (params) {
      for (const paramKey in params) {
        translated = translated.replace(`{{${paramKey}}}`, String(params[paramKey]));
      }
    }
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};